functional:
  - Пользователь может соревноваться с другим игроком в решении задачи
  - Пользователь может играть с ботом
  - Пользователь может пригласить друга по ссылке
  - Система должна вести рейтинг игроков
  - Пользователь может просматривать историю сыгранных игр

non-functional:
  - Сайт должен быть оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователей
  - Сайт должен быть адаптирован для мобильных устройств
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен выдерживать нагрузку не менее 1000 одновременных пользователей

implicit:
  - Пользователь ожидает, что интерфейс будет понятным и удобным
  - Пользователь ожидает, что ссылки и кнопки будут работать предсказуемо
  - Пользователь ожидает, что результаты игры сохраняются и не теряются
  - Пользователь ожидает, что система будет доступна 24/7 без простоев
